---
title: 终止错误 |Microsoft Docs
ms.custom: ''
ms.date: 09/13/2016
ms.reviewer: ''
ms.suite: ''
ms.tgt_pltfrm: ''
ms.topic: article
ms.assetid: b804e738-aefa-41bb-9649-f9ed897fd96c
caps.latest.revision: 8
ms.openlocfilehash: d1967fe7996f75ec5229920f7ec49aa5ff6bdbfd
ms.sourcegitcommit: 52a67bcd9d7bf3e8600ea4302d1fa8970ff9c998
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/15/2019
ms.locfileid: "72369326"
---
# <a name="terminating-errors"></a><span data-ttu-id="db09d-102">终止错误</span><span class="sxs-lookup"><span data-stu-id="db09d-102">Terminating Errors</span></span>

<span data-ttu-id="db09d-103">本主题讨论用于报告终止错误的方法。</span><span class="sxs-lookup"><span data-stu-id="db09d-103">This topic discusses the method used to report terminating errors.</span></span> <span data-ttu-id="db09d-104">它还讨论了如何从 cmdlet 内调用方法，并讨论了调用方法时 Windows PowerShell 运行时可能返回的异常。</span><span class="sxs-lookup"><span data-stu-id="db09d-104">It also discusses how to call the method from within the cmdlet, and it discusses the exceptions that can be returned by the Windows PowerShell runtime when the method is called.</span></span>

<span data-ttu-id="db09d-105">当发生终止错误时，此 cmdlet 应通过调用[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)方法报告错误消息。</span><span class="sxs-lookup"><span data-stu-id="db09d-105">When a terminating error occurs, the cmdlet should report the error by calling the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method.</span></span> <span data-ttu-id="db09d-106">此方法允许 cmdlet 发送描述引起终止错误的条件的错误记录。</span><span class="sxs-lookup"><span data-stu-id="db09d-106">This method allows the cmdlet to send an error record that describes the condition that caused the terminating error.</span></span> <span data-ttu-id="db09d-107">有关错误记录的详细信息，请参阅[Windows PowerShell 错误记录](./windows-powershell-error-records.md)。</span><span class="sxs-lookup"><span data-stu-id="db09d-107">For more information about error records, see [Windows PowerShell Error Records](./windows-powershell-error-records.md).</span></span>

<span data-ttu-id="db09d-108">如果调用了 [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) 方法，则 Windows PowerShell 运行时将永久停止执行管道，并引发[System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) 异常。</span><span class="sxs-lookup"><span data-stu-id="db09d-108">When the [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) method is called, the  Windows PowerShell runtime permanently stops the execution of the pipeline and throws a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span> <span data-ttu-id="db09d-109">任何后续尝试调用[WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject)、 [WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)或其他多个 api 时，都将导致这些调用引发了[异常情况。 Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)异常。</span><span class="sxs-lookup"><span data-stu-id="db09d-109">Any subsequent attempts to call [System.Management.Automation.Cmdlet.WriteObject](/dotnet/api/System.Management.Automation.Cmdlet.WriteObject), [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError), or several other APIs causes those calls to throw a [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception.</span></span>

<span data-ttu-id="db09d-110">如果管道中的另一个 cmdlet 报告终止错误（如果用户已请求停止管道），或者管道在完成前已暂停，则也可能会发生[Pipelinestoppedexception 异常。](/dotnet/api/System.Management.Automation.PipelineStoppedException)在于.</span><span class="sxs-lookup"><span data-stu-id="db09d-110">The [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception can also occur if another cmdlet in the pipeline reports a terminating error, if the user has asked to stop the pipeline, or if the pipeline has been halted before completion for any reason.</span></span> <span data-ttu-id="db09d-111">Cmdlet 不需要捕获[Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException)异常，除非它必须清除打开的资源或其内部状态。</span><span class="sxs-lookup"><span data-stu-id="db09d-111">The cmdlet does not need to catch the [System.Management.Automation.Pipelinestoppedexception](/dotnet/api/System.Management.Automation.PipelineStoppedException) exception unless it must clean up open resources or its internal state.</span></span>

<span data-ttu-id="db09d-112">在报告终止错误之前，cmdlet 可以写入任意数量的输出对象或非终止错误。</span><span class="sxs-lookup"><span data-stu-id="db09d-112">Cmdlets can write any number of output objects or non-terminating errors before reporting a terminating error.</span></span> <span data-ttu-id="db09d-113">但是，终止错误会永久停止管道，并且不会报告其他输出、终止错误或非终止错误。</span><span class="sxs-lookup"><span data-stu-id="db09d-113">However, the terminating error permanently stops the pipeline, and no further output, terminating errors, or non-terminating errors can be reported.</span></span>

<span data-ttu-id="db09d-114">Cmdlet 只能从名为 [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)[System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)或 [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) 输入处理方法的线程调用 [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)。</span><span class="sxs-lookup"><span data-stu-id="db09d-114">Cmdlets can call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) only from the thread that called the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) input processing method.</span></span> <span data-ttu-id="db09d-115">不要尝试从另一个线程调用[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)或[WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)的其他线程中的其他线程。</span><span class="sxs-lookup"><span data-stu-id="db09d-115">Do not attempt to call [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) or [System.Management.Automation.Cmdlet.WriteError](/dotnet/api/System.Management.Automation.Cmdlet.WriteError) from another thread.</span></span> <span data-ttu-id="db09d-116">而必须将错误发回到主线程。</span><span class="sxs-lookup"><span data-stu-id="db09d-116">Instead, errors must be communicated back to the main thread.</span></span>

<span data-ttu-id="db09d-117">Cmdlet 可能会在其[BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)实现中引发异常，即[ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)，或[的异常情况下，可能会引发异常。System.web. EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)方法。</span><span class="sxs-lookup"><span data-stu-id="db09d-117">It is possible for a cmdlet to throw an exception in its implementation of the [System.Management.Automation.Cmdlet.BeginProcessing](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing), [System.Management.Automation.Cmdlet.ProcessRecord](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord), or [System.Management.Automation.Cmdlet.EndProcessing](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing) method.</span></span> <span data-ttu-id="db09d-118">从这些方法引发的任何异常（除了停止 Windows PowerShell 主机的几个严重错误情况外）均被解释为终止错误，该错误将停止管道，而不是整个 Windows PowerShell。</span><span class="sxs-lookup"><span data-stu-id="db09d-118">Any exception thrown from these methods (except for a few severe error conditions that stop the Windows PowerShell host) is interpreted as a terminating error which stops the pipeline, but not Windows PowerShell as a whole.</span></span> <span data-ttu-id="db09d-119">（这仅适用于主 cmdlet 线程。</span><span class="sxs-lookup"><span data-stu-id="db09d-119">(This applies only to the main cmdlet thread.</span></span> <span data-ttu-id="db09d-120">通常，在由 cmdlet 生成的线程中未捕获到的异常通常是暂停 Windows PowerShell 主机。）建议使用[Throwterminatingerror \*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)而不是引发异常，因为错误记录提供了有关错误条件的其他信息，这对最终用户非常有用。</span><span class="sxs-lookup"><span data-stu-id="db09d-120">Uncaught exceptions in threads spawned by the cmdlet, in general, halt the Windows PowerShell host.) We recommend that you use [System.Management.Automation.Cmdlet.Throwterminatingerror\*](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError) rather than throwing an exception because the error record provides additional information about the error condition, which is useful to the end-user.</span></span> <span data-ttu-id="db09d-121">Cmdlet 应遵循托管代码准则，以避免捕获和处理所有异常（`catch (Exception e)`）。</span><span class="sxs-lookup"><span data-stu-id="db09d-121">Cmdlets should honor the managed code guideline against catching and handling all exceptions (`catch (Exception e)`).</span></span> <span data-ttu-id="db09d-122">仅将已知类型和预期类型的异常转换为错误记录。</span><span class="sxs-lookup"><span data-stu-id="db09d-122">Convert only exceptions of known and expected types into error records.</span></span>

## <a name="see-also"></a><span data-ttu-id="db09d-123">另请参阅</span><span class="sxs-lookup"><span data-stu-id="db09d-123">See Also</span></span>

[<span data-ttu-id="db09d-124">"BeginProcessing"。</span><span class="sxs-lookup"><span data-stu-id="db09d-124">System.Management.Automation.Cmdlet.BeginProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.BeginProcessing)

[<span data-ttu-id="db09d-125">System.web. EndProcessing. EndProcessing</span><span class="sxs-lookup"><span data-stu-id="db09d-125">System.Management.Automation.Cmdlet.EndProcessing</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.EndProcessing)

[<span data-ttu-id="db09d-126">"ProcessRecord"。</span><span class="sxs-lookup"><span data-stu-id="db09d-126">System.Management.Automation.Cmdlet.ProcessRecord</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ProcessRecord)

[<span data-ttu-id="db09d-127">System.web. Pipelinestoppedexception</span><span class="sxs-lookup"><span data-stu-id="db09d-127">System.Management.Automation.Pipelinestoppedexception</span></span>](/dotnet/api/System.Management.Automation.PipelineStoppedException)

[<span data-ttu-id="db09d-128">Throwterminatingerror \* 的 \*</span><span class="sxs-lookup"><span data-stu-id="db09d-128">System.Management.Automation.Cmdlet.Throwterminatingerror\*</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.ThrowTerminatingError)

[<span data-ttu-id="db09d-129">"WriteError"。</span><span class="sxs-lookup"><span data-stu-id="db09d-129">System.Management.Automation.Cmdlet.WriteError</span></span>](/dotnet/api/System.Management.Automation.Cmdlet.WriteError)

[<span data-ttu-id="db09d-130">Windows PowerShell 错误记录</span><span class="sxs-lookup"><span data-stu-id="db09d-130">Windows PowerShell Error Records</span></span>](./windows-powershell-error-records.md)

[<span data-ttu-id="db09d-131">编写 Windows PowerShell Cmdlet</span><span class="sxs-lookup"><span data-stu-id="db09d-131">Writing a Windows PowerShell Cmdlet</span></span>](./writing-a-windows-powershell-cmdlet.md)
